"""add is_system_noise flag to logs

Revision ID: 6523fc18e287
Revises: eb6749369eb7
Create Date: 2026-09-03 22:50:47.610349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6523fc18e287'
down_revision: Union[str, Sequence[str], None] = 'eb6749369eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_noise', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
         batch_op.drop_column('is_system_noise')

    # ### end Alembic commands ###
