"""add source field to logs and alerts

Revision ID: 92232bdb2625
Revises: 6523fc18e287
Create Date: 2026-09-04 22:50:19.061688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92232bdb2625'
down_revision: Union[str, Sequence[str], None] = '6523fc18e287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
