"""add resource column to alerts

Revision ID: dadf07176429
Revises: 5d761bb109f3
Create Date: 2026-03-05 20:25:03.581169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadf07176429'
down_revision: Union[str, Sequence[str], None] = '5d761bb109f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts',
    sa.Column('resource', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'resource')
    # ### end Alembic commands ###
