"""add source_event_id to logs for deduplication

Revision ID: eb6749369eb7
Revises: e6ea5fdd9d36
Create Date: 2026-08-28 02:51:16.972045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6749369eb7'
down_revision: Union[str, Sequence[str], None] = 'e6ea5fdd9d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_event_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_logs_source_event_id', ['source_event_id'])
        
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_logs_source_event_id', type_='unique')
        batch_op.drop_column('source_event_id')

    # ### end Alembic commands ###
